baseURL = "https://bad-montigny.fr"
title = "Badminton Club Montigny-le-Bretonneux"
author = "Thomas M"
copyright = ""
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
buildFuture = true
theme = "ponigym"
disqusShortname = "bcmb78"
paginate= 6

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
  
[outputs]
    section = ["HTML", "JSON"]

[params]
  facebook = ""
  description = ""
  mainSections = ["post", "equipe", "resultat", "event"]

[menu]
  [[menu.main]]
    identifier = "club"
    name = "Le club"
    url = "/club/"
    weight = 10
	
  [[menu.main]]
    identifier = "actu"
    name = "Actualités"
    url = "/post/"
    weight = 20
	
  [[menu.main]]
    identifier = "events"
    name = "Evènements"
    url = "/event/"
    weight = 30
	
  [[menu.main]]
    identifier = "presentation"
    name = "Présentation"
	parent = "club"
    url = "/club/presentation"
    weight = 11
  [[menu.main]]
    identifier = "bureau"
    name = "Le bureau"
	parent = "club"
    url = "/club#bureau"
    weight = 12
  [[menu.main]]
    identifier = "lieux"
    name = "Créneaux"
	parent = "club"
    url = "/club#creneaux"
    weight = 13
  [[menu.main]]
    identifier = "horaires"
    name = "Gymnases"
	parent = "club"
    url = "/club#gymnases"
    weight = 14
  [[menu.main]]
    identifier = "inscription"
    name = "S'inscrire"
	parent = "club"
    url = "/club#inscription"
    weight = 15
	
  [[menu.main]]
    identifier = "adultes"
    name = "Adultes"
    url = ""
    weight = 40
  [[menu.main]]
    identifier = "interclubs"
	parent = "adultes"
    name = "Interclubs"
    url = "/equipe/"
    weight = 41

  [[menu.main]]
    identifier = "loisirs"
	parent = "adultes"
    name = "Loisirs"
    url = "/loisirs/"
    weight = 42
	

  [[menu.main]]
    identifier = "jeunes"
    name = "Jeunes"
    url = "/jeunes/"
    weight = 40

  [[menu.main]]
	identifier = "skybad"
	name = "SkyBad"
	url = "/skybad/"
	weight = 50





