---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/tournois
  label: Tournois
  create: all
  match: "**/*"
- type: directory
  path: content/skybad
  label: Skybad
  create: all
  match: "**/*"
- type: directory
  path: content/resultat
  label: Resultat
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/loisirs
  label: Loisirs
  create: all
  match: "**/*"
- type: directory
  path: content/jeunes
  label: Jeunes
  create: all
  match: "**/*"
- type: directory
  path: content/homepage
  label: Homepage
  create: all
  match: "**/*"
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
- type: directory
  path: content/equipe
  label: Equipe
  create: all
  match: "**/*"
- type: directory
  path: content/documents_liens
  label: Documents liens
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/club
  label: Club
  create: all
  match: "**/*"
upload_dir: static/img
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
